In [54]:
# Import dependencies
import pandas as pd
from pathlib import Path
from zipfile import ZipFile
import urllib.request
import io
from io import BytesIO
from IPython.display import display
import json
import requests

In [55]:
# Table identifiers
table_dict = {
    "EV_sales_table_raw" : 20100025,
    "LFS_table_raw" : 14100391
}
table_dict

{'EV_sales_table': 20100025, 'LFS_table': 14100391}

In [56]:
base_url = "https://www150.statcan.gc.ca/t1/wds/rest/getFullTableDownloadCSV/"
language_ident = "/en"

In [57]:
def pull_statcan_table(table_name, table_ident):

        file_end = ".csv"
        url = base_url + str(table_ident) + language_ident
        # print(url)

        url_json = requests.get(url).json()
        # print(url_json)

        archive_link = url_json["object"]
        # print(archive_link)

        access_url = urllib.request.urlopen(archive_link)
        # print(access_url)
        zf=ZipFile(BytesIO(access_url.read()))
        data = zf.read(str(table_ident) + file_end)
        # print(data)

        df = pd.read_csv(io.StringIO(data.decode("utf-8")))
        display(df)

        # Save DataFrame to CSV file in raw_datasets directory
        # Define file path to save data
        filepath = Path('raw_datasets/' + table_name + file_end)
        # Allow folders and subfolders to be created is needed
        filepath.parent.mkdir(parents=True, exist_ok=True)
        # Save the file
        df.to_csv(filepath)

In [58]:
for key, value in table_dict.items():
    print(key)
    pull_statcan_table(key, value)

EV_sales_table

,REF_DATE,GEO,DGUID,Zero-Emission Vehicles Fuel Type,Vehicle type,Statistics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017-01,Canada,2016A000011124,All zero-emission vehicles,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277479871,1.1.1.1,3488.0,NaN,NaN,NaN,0
1,2017-01,Canada,2016A000011124,Battery electric,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277485216,1.2.1.1,1664.0,NaN,NaN,NaN,0
2,2017-01,Canada,2016A000011124,Plug-in hybrid electric,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277490561,1.3.1.1,1824.0,NaN,NaN,NaN,0
3,2017-01,Newfoundland and Labrador,2016A000210,All zero-emission vehicles,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277479872,2.1.1.1,NaN,..,NaN,NaN,0
4,2017-01,Newfoundland and Labrador,2016A000210,Battery electric,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277485217,2.2.1.1,NaN,..,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320695,2021-10,Taloyoak,2016A00056208087,Battery electric,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277490559,5345.2.1.1,NaN,..,NaN,NaN,0
320696,2021-10,Taloyoak,2016A00056208087,Plug-in hybrid electric,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277495904,5345.3.1.1,NaN,..,NaN,NaN,0
320697,2021-10,"Kitikmeot, Unorganized",2016A00056208098,All zero-emission vehicles,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277485215,5346.1.1.1,NaN,..,NaN,NaN,0
320698,2021-10,"Kitikmeot, Unorganized",2016A00056208098,Battery electric,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277490560,5346.2.1.1,NaN,..,NaN,NaN,0
320699,2021-10,"Kitikmeot, Unorganized",2016A00056208098,Plug-in hybrid electric,"Total, vehicle type",Number of vehicles,Units,300,units,0,v1277495905,5346.3.1.1,NaN,..,NaN,NaN,0

LFS_table

,REF_DATE,GEO,DGUID,Labour force characteristics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2006,"Corner Brook, Newfoundland and Labrador",2016S0504015,Population,Persons,249,thousands,3,v1235071748,1.1,26.3,NaN,NaN,NaN,1
1,2006,"Corner Brook, Newfoundland and Labrador",2016S0504015,Labour force,Persons,249,thousands,3,v1235071749,1.2,16.9,NaN,NaN,NaN,1
2,2006,"Corner Brook, Newfoundland and Labrador",2016S0504015,Employment,Persons,249,thousands,3,v1235071750,1.3,14.5,NaN,NaN,NaN,1
3,2006,"Corner Brook, Newfoundland and Labrador",2016S0504015,Unemployment,Persons,249,thousands,3,v1235071751,1.4,2.4,NaN,NaN,NaN,1
4,2006,"Corner Brook, Newfoundland and Labrador",2016S0504015,Not in labour force,Persons,249,thousands,3,v1235071752,1.5,9.4,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3707,2021,"Prince George, British Columbia",2016S0504970,Unemployment,Persons,249,thousands,3,v1235071975,31.4,3.2,NaN,NaN,NaN,1
3708,2021,"Prince George, British Columbia",2016S0504970,Not in labour force,Persons,249,thousands,3,v1235071976,31.5,25.3,NaN,NaN,NaN,1
3709,2021,"Prince George, British Columbia",2016S0504970,Unemployment rate,Percentage,242,units,0,v1235071977,31.6,5.7,NaN,NaN,NaN,1
3710,2021,"Prince George, British Columbia",2016S0504970,Participation rate,Percentage,242,units,0,v1235071978,31.7,68.9,NaN,NaN,NaN,1
3711,2021,"Prince George, British Columbia",2016S0504970,Employment rate,Percentage,242,units,0,v1235071979,31.8,64.8,NaN,NaN,NaN,1